version: '3'
services:
  algo:
    build:
      context: ./algo
      dockerfile: Dockerfile.algo
    ports:
      - "8080:8080"
    command: ./ChessCraftAlgo
    depends_on:
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: chess
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
