# First stage: Install dependencies and build
FROM node:14 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install

# Second stage: Create the final image
FROM node:14
WORKDIR /app
# Copy the application code
COPY . .
# Copy node_modules from the builder stage
COPY --from=builder /app/node_modules /app/node_modules

EXPOSE 3001
# Run the app
CMD ["node", "server.js"]
